export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Cours du soutient maths,physique et chimie de la 6éme à la terminale, on vous souhaite les bienvenus .",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc:"Cours de soutient en algorithmique et programmation pour les niveaux L1 jusqu'a L3 .",
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Programme de soutient de primaire au lycée ",
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc:"Profiter de cours du soutient à domicile, c'est pas la pien de déplacer !",
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc:"N'ésitez pas à nos contacter on reste a votre disposition !",
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Profiter d'une formation de langue complete .",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc:"Vous cherchez le meilleur offre quantité/Prix ... contacter nous rapidment !!",
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc:"Cours particulier de soutient scolaire ",
   
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc:"Profiter des cours du soutient a distance ou a domicile !",
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    place: "Ruiseau,Alger,Algeria",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
